import { test, expect } from '@playwright/test';

async function login(page, email, password) {
  await page.goto('/login');
  await page.getByLabel('Correo electrónico').fill(email);
  await page.getByLabel('Contraseña', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await expect(page).toHaveURL(/\/$/);
  await expect(page.getByRole('link', { name: 'Mis vehículos', exact: true })).toBeVisible();
}

test('publicación con cinco fotos, dos postores en vivo, cierre y notificaciones', async ({ browser, page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Explora el inventario' })).toBeVisible();
  await page.screenshot({ path: 'test-results/inventario-desktop.png', fullPage: true });
  await page.getByRole('link', { name: 'Publicar vehículo', exact: true }).click();
  await expect(page).toHaveURL(/\/login\?next=/);
  await login(page, 'vendedor@subastas.test', 'Vendedor123!');
  await page.goto('/publicar');
  await page.getByLabel('Año', { exact: true }).fill('2020');
  await page.getByLabel('Tipo de artículo').fill('Automóvil');
  await page.getByLabel('Marca', { exact: true }).fill('Toyota');
  await page.getByLabel('Modelo', { exact: true }).fill('Corolla');
  await page.getByLabel('Motor', { exact: true }).fill('1.8 L');
  await page.getByLabel('Transmisión').selectOption('Automática');
  await page.getByLabel('Combustible', { exact: true }).selectOption('Gasolina');
  await page.getByLabel('Tracción').selectOption('FWD');
  await page.getByLabel('Número de cilindros').fill('4');
  await page.getByLabel('Estado de daño').selectOption('Verde');
  await page.getByLabel('Descripción').fill('Prueba de interfaz sobre SQLite aislado.');
  await page.getByRole('button', { name: 'Guardar ficha' }).click();
  await expect(page).toHaveURL(/\/vehiculos\/\d+\/editar/);
  const vehicleUrl = page.url().replace('/editar', '');
  const image = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64');
  await page.locator('#photo-files').setInputFiles(Array.from({ length: 5 }, (_, i) => ({ name: `foto${i}.png`, mimeType: 'image/png', buffer: image })));
  await page.getByRole('button', { name: 'Subir fotografías' }).click();
  await expect(page.locator('#photo-count')).toHaveText('5 / 5 mínimo');
  await expect(page.getByRole('button', { name: 'Publicar subasta' })).toBeEnabled();
  await page.getByLabel('Precio base (Q)').fill('20000.00');
  const starts = Date.now() + 12000, ends = starts + 32000;
  await page.getByLabel('Fecha y hora de inicio').fill(new Date(starts).toISOString().slice(0, 19));
  await page.getByLabel('Fecha y hora de cierre').fill(new Date(ends).toISOString().slice(0, 19));
  await page.getByRole('button', { name: 'Publicar subasta' }).click();
  await expect(page).toHaveURL(vehicleUrl);
  await expect(page.getByRole('heading', { name: '2020 Toyota Corolla' })).toBeVisible();
  await page.getByRole('button', { name: 'Siguiente fotografía' }).click();
  await expect(page.locator('#gallery-counter')).toHaveText('2 / 5');
  const context1 = await browser.newContext({ baseURL: 'http://127.0.0.1:8010', timezoneId: 'UTC' });
  const context2 = await browser.newContext({ baseURL: 'http://127.0.0.1:8010', timezoneId: 'UTC' });
  const bidder1 = await context1.newPage(), bidder2 = await context2.newPage();
  bidder1.on('pageerror', error => errors.push(error.message)); bidder2.on('pageerror', error => errors.push(error.message));
  await login(bidder1, 'postor1@subastas.test', 'Postor123!');
  await login(bidder2, 'postor2@subastas.test', 'Postor123!'.replace('1', '2'));
  await bidder1.goto(vehicleUrl); await bidder2.goto(vehicleUrl);
  await expect(bidder1.locator('#bid-button')).toBeEnabled({ timeout: 25000 });
  await bidder1.getByLabel('Tu oferta (Q)').fill('21000.00');
  await bidder1.getByRole('button', { name: 'Realizar oferta' }).click();
  await bidder1.getByRole('button', { name: 'Confirmar oferta' }).click();
  await expect(bidder1.locator('#personal-state')).toContainText('Vas ganando');
  await expect(bidder2.locator('#current-price')).toContainText('21,000.00');
  await bidder2.getByLabel('Tu oferta (Q)').fill('22000.00');
  await bidder2.getByRole('button', { name: 'Realizar oferta' }).click();
  await bidder2.getByRole('button', { name: 'Confirmar oferta' }).click();
  await expect(bidder2.locator('.form-error')).toContainText('mínimo vigente');
  await bidder2.getByLabel('Tu oferta (Q)').fill('23100.00');
  await bidder2.getByRole('button', { name: 'Realizar oferta' }).click();
  await bidder2.getByRole('button', { name: 'Confirmar oferta' }).click();
  await expect(bidder2.locator('#personal-state')).toContainText('Vas ganando');
  await expect(bidder1.locator('#personal-state')).toContainText('fue superada');
  await bidder1.screenshot({ path: 'test-results/subasta-desktop.png', fullPage: true });
  await expect(bidder2.locator('#personal-state')).toContainText('¡Ganaste', { timeout: 45000 });
  await expect(bidder2.locator('#bid-button')).toBeDisabled();
  await bidder2.goto('/mis-pujas');
  await bidder2.getByRole('tab', { name: 'Subastas ganadas' }).click();
  await expect(bidder2.locator('#bids-list')).toContainText('23,100.00');
  await bidder1.goto('/notificaciones');
  await expect(bidder1.locator('#notice-list')).toContainText('superada');
  await bidder1.getByRole('button', { name: 'Marcar como leída' }).first().click();
  await expect(bidder1.locator('#notice-list .badge').filter({ hasText: 'Leída' }).first()).toBeVisible();
  await page.goto('/mis-vehiculos');
  await expect(page.locator('#vehicles')).toContainText('Corolla');
  await page.goto('/');
  await page.getByLabel('Subasta', { exact: true }).selectOption('Finalizada');
  await page.getByRole('button', { name: 'Aplicar filtros' }).click();
  await expect(page.locator('#vehicles')).toContainText('Corolla');
  await expect(page.locator('#global-error')).toBeHidden();
  await context1.close(); await context2.close();
  expect(errors).toEqual([]);
});

test('registro, login con validación y navegación móvil', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await expect(page.locator('#results-count')).not.toContainText('Consultando');
  await page.screenshot({ path: 'test-results/inventario-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.goto('/registro');
  await page.getByLabel('Nombre', { exact: true }).fill('Prueba');
  await page.getByLabel('Apellido').fill('Móvil');
  await page.getByLabel('Teléfono').fill('55551234');
  await page.getByLabel('Correo electrónico').fill('movil@example.test');
  await page.getByLabel('Contraseña', { exact: true }).fill('Movil123!');
  await page.getByLabel('Confirmar contraseña').fill('Diferente123!');
  await page.getByRole('button', { name: 'Crear cuenta' }).click();
  await expect(page.locator('.form-error')).toContainText('no coinciden');
  await page.getByLabel('Confirmar contraseña').fill('Movil123!');
  await page.getByRole('button', { name: 'Crear cuenta' }).click();
  await expect(page).toHaveURL(/\/login\?registered/);
  await page.getByLabel('Correo electrónico').fill('movil@example.test');
  await page.getByLabel('Contraseña', { exact: true }).fill('Invalida123!');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await expect(page.locator('.form-error')).toContainText('incorrectos');
  await page.getByLabel('Contraseña', { exact: true }).fill('Movil123!');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await expect(page).toHaveURL(/\/$/);
  await page.getByRole('link', { name: 'Mis vehículos', exact: true }).click();
  await expect(page.locator('#vehicles')).toContainText('Tu próxima publicación');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.getByRole('button', { name: 'Salir', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Iniciar sesión', exact: true })).toBeVisible();
});
